### PR TITLE
Custom event for style updates

### PR DESCRIPTION
**Pull request by redaxmedia**
Can be tested this way:

<pre>$(window).on('viewport-units-buggyfill-style', function (event) {
    alert(event.type);
});</pre>

### CODE REVIEW

**Comment by redaxmedia** [comment]
It would be great to have custom <code>viewport-units-buggyfill-init</code> too but I don't know the right place were to put it to...

**Comment by rodneyrehm** [comment]
PR for issue #62 

---

This is going to fail in IE10 and older, because it does not know the CustomEvent constructor. You'll need to add a [polyfill](https://github.com/krambuhl/custom-event-polyfill/blob/master/custom-event-polyfill.js) for this.

> It would be great to have custom viewport-units-buggyfill-init too but I don't know the right place were to put it to...

what do you intend to do with it? I'd say [before initializing the hacks](https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L122) is a good time?

**Comment by redaxmedia** [comment]
I'd like to add and remove classes to hide parts in the website that will be processed and look ugly before the buggyfill finished processing.

<pre>$(window).on('viewport-units-buggyfill-init viewport-units-buggyfill-style', function (event) {
    if (event.type === 'viewport-units-buggyfill-init') {
    //add buggy class to hide something
    } else {
    //remove buggy class to hide something
    }
});</pre>

**Comment by redaxmedia** [comment]
Were is the best place to add the polyfill inside your core?

**Comment by rodneyrehm** [comment]
> Were is the best place to add the polyfill inside your core?

since we're talking about few lines of code, I guess I'd just copy-paste it (with linking to the source) [before the private functions](https://github.com/rodneyrehm/viewport-units-buggyfill/blob/master/viewport-units-buggyfill.js#L73).

**Comment by redaxmedia** [comment]
Let me test it once you merged it to the master.

**Comment by rodneyrehm** [comment]
Why do you need this merged to master to test it?

```bash
bower link $moduleName
npm link $moduleName
```

**Comment by redaxmedia** [comment]
I allready tested it with my fork, but not with the polyfill.

**Comment by rodneyrehm** [comment]
I don't understand. you still need to add the polyfill to your PR anyway?!

**Comment by redaxmedia** [comment]
Lost in conversation, I thought you are going to add it. Anyway - I updated my fork. The pull request can be merged.

**Pull request merged**
